apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencloud.fullname" . }}-search
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: search
spec:
  type: ClusterIP
  ports:
    - port: 9224
      targetPort: debug
      protocol: TCP
      name: debug
    - port: 9220
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "opencloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: search
