---
apiVersion: jetstream.nats.io/v1beta2
kind: Account
metadata:
  name: opencloud-nats
spec:
  name: opencloud-nats
  servers:
    - nats://nats.opencloud-nats.svc.cluster.local:4222

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: main-queue
spec:
  account: opencloud-nats
  allowRollup: false
  description: OpenCloud message bus
  discard: old
  duplicateWindow: "2m0s"
  maxAge: "168h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 0
  name: main-queue
  noAck: false
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: file
  subjects:
    - main-queue

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-cache-userinfo
spec:
  account: opencloud-nats
  allowRollup: true
  description: OpenCloud proxy userinfo cache
  denyDelete: true
  discard: new
  duplicateWindow: "10s"
  maxAge: "10s"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_cache-userinfo
  noAck: false
  allowDirect: false # differs from the OpenCloud product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.cache-userinfo.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-userlog
spec:
  account: opencloud-nats
  allowRollup: true
  description: OpenCloud userlog store
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "336h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_userlog
  noAck: false
  allowDirect: false # differs from the OpenCloud product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: file
  subjects:
    - $KV.userlog.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-activitylog
spec:
  account: opencloud-nats
  allowRollup: true
  description: OpenCloud activitylog store
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "336h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_activitylog
  noAck: false
  allowDirect: false # differs from the OpenCloud product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: file
  subjects:
    - $KV.activitylog.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-postprocessing
spec:
  account: opencloud-nats
  allowRollup: true
  description: OpenCloud postprocessing store
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "168h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_postprocessing
  noAck: false
  allowDirect: false # differs from the OpenCloud product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: file
  subjects:
    - $KV.postprocessing.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-ids-storage-users
spec:
  account: opencloud-nats
  allowRollup: true
  description: OpenCloud storageusers id cache
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "24h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_ids-storage-users
  noAck: false
  allowDirect: false # differs from the OpenCloud product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.ids-storage-users.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-storage-users
spec:
  account: opencloud-nats
  allowRollup: true
  description: OpenCloud storageusers cache
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "24h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_storage-users
  noAck: false
  allowDirect: false # differs from the OpenCloud product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.storage-users.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-eventhistory
spec:
  account: opencloud-nats
  allowRollup: true
  description: OpenCloud userlog store
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "336h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_eventhistory
  noAck: false
  allowDirect: false # differs from the OpenCloud product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: file
  subjects:
    - $KV.eventhistory.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-service-registry
spec:
  account: opencloud-nats
  allowRollup: true
  description: OpenCloud service registry
  denyDelete: true
  discard: new
  duplicateWindow: "30s"
  maxAge: "30s"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_service-registry
  noAck: false
  allowDirect: false # differs from the OpenCloud product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.service-registry.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-settings-cache
spec:
  account: opencloud-nats
  allowRollup: true
  description: OpenCloud settings cache
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "10m0s"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_settings-cache
  noAck: false
  allowDirect: false # differs from the OpenCloud product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.settings-cache.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-storage-system
spec:
  account: opencloud-nats
  allowRollup: true
  description: OpenCloud storagesystem cache
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "24h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_storage-system
  noAck: false
  allowDirect: false # differs from the OpenCloud product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.storage-system.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-cache-roles
spec:
  account: opencloud-nats
  allowRollup: true
  description: OpenCloud graph roles cache
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "24h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_cache-roles
  noAck: false
  allowDirect: false # differs from the OpenCloud product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.cache-roles.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-proxy
spec:
  account: opencloud-nats
  allowRollup: true
  description: OpenCloud ocs and proxy signing keys
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "24h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_proxy
  noAck: false
  allowDirect: false # differs from the OpenCloud product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.proxy.>

---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: kv-opencloud-pkg
spec:
  account: opencloud-nats
  allowRollup: true
  description: OpenCloud settings roles cache
  denyDelete: true
  discard: new
  duplicateWindow: "2m0s"
  maxAge: "24h"
  maxBytes: -1
  maxConsumers: -1
  maxMsgs: -1
  maxMsgSize: -1
  maxMsgsPerSubject: 1
  name: KV_opencloud-pkg
  noAck: false
  allowDirect: false # differs from the OpenCloud product default, but it needs to be like this, reasoning see: https://github.com/owncloud/ocis/issues/8432
  preventDelete: false
  preventUpdate: false
  replicas: 3
  retention: limits
  storage: memory
  subjects:
    - $KV.opencloud-pkg.>